### ISSUE TITLE
Production readiness - launch checklist 🚀 

### ISSUE THREAD

**Issue by roadlittledawn** [roadlittledawn/kevincmaginnis#13]
## Summary

Checklist to launch new site. Confining re-launch to only include parity with current site, give or take few things.

## Acceptance criteria
- [x] Update typography to use gil sans or similar font (in progress)
- [x] Update left sidebar nav to match current one  (in progress)
- [x] Update header text to align with image gallery @melo616 
- [x] Add mobile nav @roadlittledawn 
- [x] Add rest of slides
- [x] Update slide nav controls (first, last, add icons) @melo616 
- [x] Fix bug where slide order does not match order in yaml
- [x] Remove unused images (via script) @melo616 
- [x] Migrate Contact page content  @melo616 
- [x] #3 @roadlittledawn 
- [x] Update GoDaddy DNS to point to netlify @roadlittledawn 

## Helpful links
